// AUTO-GENERATED by scripts/gen-i18n-resources.js — do not edit by hand.
// Run `node scripts/gen-i18n-resources.js` after adding a language or namespace.
import en_auth from './locales/en/auth.json';
import en_chat from './locales/en/chat.json';
import en_common from './locales/en/common.json';
import en_cv from './locales/en/cv.json';
import en_goals from './locales/en/goals.json';
import en_home from './locales/en/home.json';
import en_misc from './locales/en/misc.json';
import en_opps from './locales/en/opps.json';
import en_profile from './locales/en/profile.json';
import en_settings from './locales/en/settings.json';

export const resources = {
    en: {
        auth: en_auth,
        chat: en_chat,
        common: en_common,
        cv: en_cv,
        goals: en_goals,
        home: en_home,
        misc: en_misc,
        opps: en_opps,
        profile: en_profile,
        settings: en_settings,
    },
} as const;

export const namespaces = Object.keys(resources.en);
