-- Edutu For You — admin-managed beneficiary impact stories.
--
-- The nine seeded rows are COMPOSITES: situations drawn from user research,
-- illustrated with stock photography, describing nobody in particular. The
-- public page renders an attribution line for any row with is_composite = true.
--
-- When a real, consented story replaces one of these, the admin clears
-- is_composite and the disclosure disappears for that story alone. Do not
-- change the column default: an unlabelled invented testimonial is a
-- fabricated endorsement, and the default is what stops that happening by
-- accident.

CREATE TABLE IF NOT EXISTS public.impact_stories (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          text NOT NULL UNIQUE,
  name          text NOT NULL,
  age           integer,
  place         text NOT NULL,
  outcome       text NOT NULL,
  portrait      text NOT NULL,
  portrait_alt  text NOT NULL,
  hero_image    text NOT NULL,
  hero_alt      text NOT NULL,
  quote         text NOT NULL,
  teaser        text NOT NULL,
  chapters      jsonb NOT NULL DEFAULT '[]'::jsonb,
  stats         jsonb NOT NULL DEFAULT '[]'::jsonb,
  barrier       text,
  is_composite  boolean NOT NULL DEFAULT true,
  status        text NOT NULL DEFAULT 'published',
  sort_order    integer NOT NULL DEFAULT 0,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  CONSTRAINT impact_stories_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_impact_stories_status
  ON public.impact_stories (status, sort_order);

ALTER TABLE public.impact_stories ENABLE ROW LEVEL SECURITY;

-- Reads go through the public API, which uses the service role. Anonymous
-- clients get nothing directly; writes are admin-only via the backend.
DROP POLICY IF EXISTS impact_stories_public_read ON public.impact_stories;
CREATE POLICY impact_stories_public_read
  ON public.impact_stories FOR SELECT
  TO anon, authenticated
  USING (status = 'published');

INSERT INTO public.impact_stories
  (slug, name, age, place, outcome, portrait, portrait_alt, hero_image, hero_alt,
   quote, teaser, chapters, stats, barrier, sort_order)
VALUES
  ('aisha-kano', 'Aisha', 19, 'Kano, Nigeria', 'Fully-funded fellowship', 'https://images.unsplash.com/photo-1770235621081-030607a06cee?w=600&h=800&q=80&auto=format&fit=crop', 'A young woman studying at her desk with an open book', 'https://images.unsplash.com/photo-1516182823370-7a5fa91445c3?w=1600&h=900&q=80&auto=format&fit=crop', 'A young woman writing in a notebook outdoors', 'I could write the code. I could not write the paragraph about myself.', 'She taught herself Python on a phone with a cracked screen. The barrier was never the coursework.', '[{"heading": "Three apps, one cracked screen", "body": ["Aisha learned to code in fifteen-minute pieces, between customers at her mother''s shop in Kano. The phone she learned on had a crack running corner to corner; she got used to reading around it. By nineteen she had built three small apps, and the shop still runs its stock count on one of them.", "Nobody around her wrote software. There was no teacher to ask, no cohort to compare herself against, and no way to know whether what she was building was any good. She assumed it was not, because the only benchmark she had was the polished work of strangers on the internet."]}, {"heading": "The fellowship that had been open for two years", "body": ["The fellowship she eventually applied to had existed for two years before she heard of it. It was fully funded, it was open to exactly her profile, and it had already run twice without a single applicant from her state.", "It had not been hidden. It was on a website, in English, behind three clicks \u2014 and there was simply no mechanism by which the information would ever have reached her. Discovery was the whole gap."]}, {"heading": "A genre of writing nobody teaches", "body": ["When she found it, the application asked for a CV, a personal statement and two references. She had never written any of the three, and neither had anyone she could ask.", "This is the part people underestimate. Aisha could do the technical work the fellowship existed to fund. What stopped her for six weeks was a one-page document about herself, written in a register she had never been taught, for readers whose expectations nobody had ever described to her.", "The coaching did not write it for her. It told her what the funder was actually asking for underneath the question, and what a strong answer looked like \u2014 the thing a well-connected applicant gets for free from a parent, a teacher or a friend who has done it before."]}]'::jsonb, '[{"value": "2 years", "label": "the fellowship was open before she heard of it"}, {"value": "6 weeks", "label": "stalled on the personal statement, not the work"}, {"value": "3", "label": "apps built before she believed she was a developer"}]'::jsonb, 'The barrier was never the coursework. It was a CV she had no idea how to write.', 0),
  ('kofi-kumasi', 'Kofi', 23, 'Kumasi, Ghana', 'Global cohort place', 'https://images.unsplash.com/photo-1620829813573-7c9e1877706f?w=600&h=800&q=80&auto=format&fit=crop', 'A young man working at a laptop', 'https://images.unsplash.com/photo-1593910409015-59ae3c6aff04?w=1600&h=900&q=80&auto=format&fit=crop', 'A young man working at a laptop in low light', 'I applied to forty things. I should have applied to four.', 'He graduated top of his class into three years of rejection. The volume was never the problem.', '[{"heading": "Forty applications, three years", "body": ["Kofi finished top of his cohort and then spent three years collecting rejections. He was not casual about it \u2014 he applied to more than forty programmes, several of them twice, and kept a spreadsheet.", "The spreadsheet is the detail that stays with you. He was organised, he was persistent, and he was pointed almost entirely at the wrong targets."]}, {"heading": "Nothing was doing the filtering", "body": ["Most of what he applied to wanted five years of experience, or a different passport, or a research background he did not have. None of the listings said so in a way you could act on. Eligibility was buried in a PDF, or implied, or simply assumed.", "So the filtering fell to him \u2014 and filtering forty opportunities properly is a research project, not an evening. Each mis-aimed application cost him two evenings and a little more belief that the problem was him."]}, {"heading": "The four that fit", "body": ["There were four programmes in that same feed he was genuinely competitive for. He never found them.", "What changed was not effort. It was that something else took on the eligibility read \u2014 country, level, field, deadline \u2014 and handed him a short list he could take seriously. He applied to four things that year instead of forty, and prepared properly for each.", "Rejection did not stop. It just stopped being random."]}]'::jsonb, '[{"value": "40+", "label": "applications sent over three years"}, {"value": "4", "label": "he was actually eligible for"}, {"value": "0", "label": "listings that stated eligibility plainly"}]'::jsonb, 'His problem was applying to the wrong forty things instead of the right four.', 1),
  ('halima-kakuma', 'Halima', 17, 'Kakuma, Kenya', 'Secondary scholarship', 'https://images.unsplash.com/photo-1747021941314-4179268d6258?w=600&h=800&q=80&auto=format&fit=crop', 'A young student outdoors, looking at the camera', 'https://images.unsplash.com/photo-1648301033733-44554c74ec50?w=1600&h=900&q=80&auto=format&fit=crop', 'Students working together at a classroom desk', 'Everything I do online, I do on someone else''s data bundle.', 'She shares a data bundle with four other people. Her study time is measured in megabytes.', '[{"heading": "Study time measured in megabytes", "body": ["Halima is seventeen, lives in a refugee settlement, and shares a data bundle with four other people. Her available study time is not measured in hours. It is measured in megabytes, and when it runs out it runs out for everyone.", "She is a good student. That was never in question. What was in question was whether the internet would let her be one."]}, {"heading": "Six megabytes of hero video", "body": ["Most scholarship portals are built by people who have never had to think about this. A landing page that loads six megabytes of autoplaying video costs her a week of browsing. A form that times out and loses her answers costs her the entire attempt, and there is no guarantee of another window.", "She had abandoned three applications this way before anyone asked why. From the other side it looks like a candidate who did not follow through."]}, {"heading": "The product is that it loads", "body": ["For Halima the promise of an opportunity platform is not the intelligence. It is that the thing opens at all \u2014 in a language she reads, on the phone she actually owns, without spending the bundle before she reaches the apply button.", "Every decision behind Edutu For You is downstream of her: keep pages light, keep drafts saved, keep the deadline reminders working over SMS-grade connections, and never assume a second attempt is free."]}]'::jsonb, '[{"value": "5", "label": "people sharing one data bundle"}, {"value": "3", "label": "applications abandoned to timeouts"}, {"value": "1", "label": "attempt she can usually afford"}]'::jsonb, 'For Halima, low-bandwidth access is not a feature of the product. It is the product.', 2),
  ('chipo-bulawayo', 'Chipo', 21, 'Bulawayo, Zimbabwe', 'Agri-tech grant', 'https://images.unsplash.com/photo-1512361436605-a484bdb34b5f?w=600&h=800&q=80&auto=format&fit=crop', 'A young woman in glasses looking at the camera', 'https://images.unsplash.com/photo-1492462543947-040389c4a66c?w=1600&h=900&q=80&auto=format&fit=crop', 'A young person walking through a busy street', 'I was told grants were for people with offices.', 'She had run a working irrigation business for two years and did not believe she counted as a founder.', '[{"heading": "A business she did not call a business", "body": ["Chipo had been selling drip-irrigation kits to smallholder farmers around Bulawayo for two years. She had customers, repeat orders, a supplier and a margin.", "She did not describe herself as a founder, because in her mind founders had offices, registration certificates and pitch decks. She had a notebook and a phone."]}, {"heading": "The self-disqualification problem", "body": ["The most expensive thing in her way was not a form. It was a belief that grant programmes were for other people \u2014 better-dressed, better-connected, further along.", "This is the failure mode nobody designs for. Every eligibility filter in the world does not help someone who has already filtered themselves out before reading the criteria.", "What moved her was seeing the criteria stated plainly next to what she already had, and realising she cleared them. Not encouragement. Evidence."]}, {"heading": "Translating a notebook into an application", "body": ["The work after that was translation. Two years of orders in a notebook became traction. Her supplier relationship became a supply chain. The farmers who kept re-ordering became retention.", "None of that was invention. It was describing what she had already built in the vocabulary the people with money happen to use."]}]'::jsonb, '[{"value": "2 years", "label": "trading before she called it a business"}, {"value": "0", "label": "grant applications attempted before"}, {"value": "1", "label": "notebook, translated into traction"}]'::jsonb, 'She met the criteria for two years before anyone showed her the criteria.', 3),
  ('emeka-enugu', 'Emeka', 22, 'Enugu, Nigeria', 'Exchange programme place', 'https://images.unsplash.com/photo-1533469513-03bfed91f496?w=600&h=800&q=80&auto=format&fit=crop', 'A young man in glasses looking at the camera', 'https://images.unsplash.com/photo-1685538856920-9c7cdd86a49c?w=1600&h=900&q=80&auto=format&fit=crop', 'A young man sitting outdoors with his phone', 'I kept being told my English was the problem. It wasn''t.', 'First in his family to finish secondary school, and the first to try writing an essay nobody could check.', '[{"heading": "Nobody to read the draft", "body": ["Emeka was the first person in his family to finish secondary school, which meant he was also the first to attempt an application essay with nobody at home able to read it back to him.", "He wrote seven drafts of one essay. Each one he judged entirely on his own, in a vacuum, against a standard he was guessing at."]}, {"heading": "Fluency was never the issue", "body": ["He had been told twice that his English let him down. It was not true, and it did real damage. His English was fine. What he was missing was structure \u2014 the shape a selection panel expects an answer to take, and the difference between describing an experience and making an argument with it.", "That is a learnable thing, and it takes about an hour to explain. Most applicants get that hour from a teacher, a sibling or a friend who has already been through it. Emeka had nobody in that position, so he substituted six more drafts for one conversation."]}, {"heading": "One conversation, one draft", "body": ["The eighth draft was not more polished. It was differently organised \u2014 a claim, then evidence from his own life, then what it meant for what he wanted to do next.", "He submitted it in a week rather than a term, and spent the time he got back on the rest of the application."]}]'::jsonb, '[{"value": "7", "label": "drafts written with no reader"}, {"value": "1", "label": "conversation that changed the structure"}, {"value": "1st", "label": "in his family to finish secondary school"}]'::jsonb, 'He was never short of ability or English. He was short of one hour from someone who had done it before.', 4),
  ('fatou-dakar', 'Fatou', 20, 'Dakar, Senegal', 'Francophone fellowship', 'https://images.unsplash.com/photo-1611877247362-93a1536ad38e?w=600&h=800&q=80&auto=format&fit=crop', 'A young woman smiling at the camera', 'https://images.unsplash.com/photo-1773921405175-73a401883099?w=1600&h=900&q=80&auto=format&fit=crop', 'A graduate sitting outdoors in cap and gown', 'The opportunities existed in my language. The lists didn''t.', 'Francophone West Africa is a third of the continent''s students and a fraction of what most opportunity lists cover.', '[{"heading": "A search that returns nothing", "body": ["Fatou studies in French, thinks in Wolof and French, and reads English slowly and with effort. Almost every scholarship aggregator she found was English-first, and quietly assumed its users were too.", "The programmes she was eligible for did exist \u2014 francophone fellowships, regional funds, French-language exchanges. They were simply not on the lists that reached her."]}, {"heading": "Language as an eligibility filter nobody declared", "body": ["This is a structural exclusion, not a personal one. When the discovery layer is English-only, an entire linguistic region is filtered out before eligibility is ever assessed \u2014 and then described, later, as harder to reach.", "Fatou was not hard to reach. She was searching, consistently, in the wrong index."]}, {"heading": "Reading in the language you think in", "body": ["Reading an opportunity in your own language is not a convenience. It changes what you notice: the caveat in the eligibility line, the thing the funder says they care about, the deadline that is a submission date and not a decision date.", "Fatou did not need help understanding opportunities. She needed them to arrive in a language she could read at full speed."]}]'::jsonb, '[{"value": "9", "label": "languages Edutu now surfaces opportunities in"}, {"value": "0", "label": "francophone listings on the aggregators she tried"}, {"value": "~1/3", "label": "of the continent''s students study in French"}]'::jsonb, 'She was never hard to reach. The index she was searching simply did not include her.', 5),
  ('brian-kisumu', 'Brian', 24, 'Kisumu, Kenya', 'Engineering scholarship', 'https://images.unsplash.com/photo-1546525848-3ce03ca516f6?w=600&h=800&q=80&auto=format&fit=crop', 'A young man with a backpack outdoors', 'https://images.unsplash.com/photo-1643488422823-ca046d82123b?w=1600&h=900&q=80&auto=format&fit=crop', 'A graduate in cap and gown on the phone', 'Every deadline I missed, I missed while working.', 'He rode a boda-boda six days a week to fund a diploma, and lost opportunities to the calendar rather than the competition.', '[{"heading": "Funding your own education by the hour", "body": ["Brian rode a motorbike taxi six days a week to pay for a diploma he was taking part-time. His study happened after nine at night, and his application admin happened whenever it could.", "He was not short of drive. He was short of the one thing applications quietly demand: unbroken attention arriving at the right moment."]}, {"heading": "Losing to the calendar", "body": ["Three scholarships passed him in eighteen months. He was eligible for all three. He missed one entirely, found one four days before closing with no time to gather documents, and submitted the third in a rush that showed.", "None of those were losses to a better candidate. They were losses to a calendar nobody was holding for him."]}, {"heading": "Something that remembers on your behalf", "body": ["What actually changed his year was unglamorous: deadlines tracked, documents kept in one place, and a reminder that arrived early enough to be useful rather than the night before.", "For someone with time to spare, that is a convenience. For someone working six days a week, it is the difference between applying and not."]}]'::jsonb, '[{"value": "6 days", "label": "a week working to fund his own study"}, {"value": "3", "label": "scholarships missed to timing, not merit"}, {"value": "4 days", "label": "notice on the one he nearly made"}]'::jsonb, 'He never lost to a better candidate. He lost to a calendar nobody was holding for him.', 6),
  ('naledi-soweto', 'Naledi', 18, 'Soweto, South Africa', 'Full bursary', 'https://images.unsplash.com/photo-1612214495858-4f32b96155a7?w=600&h=800&q=80&auto=format&fit=crop', 'A young graduate smiling in cap and gown', 'https://images.unsplash.com/photo-1777186476863-7dca35c38863?w=1600&h=900&q=80&auto=format&fit=crop', 'A young graduate in cap and gown', 'I thought bursaries were something you got offered, not something you applied for.', 'She finished near the top of her year without knowing that funding was something you go and ask for.', '[{"heading": "Excellent, and uninformed", "body": ["Naledi finished matric near the top of her year. She also finished it believing that bursaries arrived \u2014 that someone noticed you, and an offer followed.", "It is an entirely reasonable belief if nobody has told you otherwise. It is also the single most expensive misunderstanding a talented eighteen-year-old can hold, because the application window closes while you are waiting to be discovered."]}, {"heading": "The information is free and still doesn''t arrive", "body": ["Nothing about the bursaries she qualified for was secret. The criteria were published. The forms were free. The deadlines were public.", "And none of it reached her, because publication is not distribution. A thing being available is not the same as a specific person finding out about it in time to act."]}, {"heading": "Applying, on purpose", "body": ["She applied to five funds in one season, having applied to none in her life before. Two came back positively.", "The shift was not academic. She had already done that part. The shift was learning that funding is a thing you pursue."]}]'::jsonb, '[{"value": "0", "label": "bursary applications before that season"}, {"value": "5", "label": "sent once she knew they existed"}, {"value": "R0", "label": "cost of the information she never received"}]'::jsonb, 'Publication is not distribution. The information was free, public — and never reached her.', 7),
  ('yohannes-addis', 'Yohannes', 23, 'Addis Ababa, Ethiopia', 'Data fellowship', 'https://images.unsplash.com/photo-1729691031378-d63d7e81bb38?w=600&h=800&q=80&auto=format&fit=crop', 'A young man in a shirt and tie', 'https://images.unsplash.com/photo-1622295023876-0cdf583c41f6?w=1600&h=900&q=80&auto=format&fit=crop', 'A young man reading beside a laptop', 'I had the skills and no way to prove them.', 'Self-taught statistics, real analysis work, and no certificate that any selection panel recognised.', '[{"heading": "Skills without paperwork", "body": ["Yohannes taught himself statistics from free courses and had done genuine analysis work \u2014 for a clinic, for a small logistics firm, unpaid and then barely paid.", "What he did not have was a credential any panel recognised. His experience was real and completely illegible to the people making decisions."]}, {"heading": "The evidence problem", "body": ["Selection panels do not reward ability directly. They reward legible evidence of ability, and those are different things.", "Most advice at this point is to get a certificate, which costs money he did not have. The more useful move was assembling what he already had into evidence: a written case study of the clinic work, a short portfolio, and two people willing to confirm what he had done.", "None of that was new work. It was making existing work visible."]}, {"heading": "Legibility, not luck", "body": ["He applied to a data fellowship with the same skills he had held for two years, presented so that a stranger could verify them in four minutes.", "That is what most of application coaching actually is. Not improving the candidate \u2014 making the candidate legible."]}]'::jsonb, '[{"value": "2 years", "label": "of real analysis work, unrecognised"}, {"value": "0", "label": "formal credentials"}, {"value": "4 min", "label": "for a stranger to verify it, once assembled"}]'::jsonb, 'Panels reward legible evidence of ability, not ability. Nobody had ever told him those were different.', 8)
ON CONFLICT (slug) DO NOTHING;
