import { communityCallReducer, initialCommunityCallState } from '../features/community-calls/useCommunityCall';
const call={id:'c',groupId:'g',title:'Check-in',scheduledFor:'2026-08-06T19:00:00Z',durationMinutes:30,status:'live' as const,createdBy:'u',startedBy:'u',endedBy:null,startedAt:'2026-08-06T19:00:00Z',ringExpiresAt:null,endedAt:null,cancelledAt:null,failureCode:null,createdAt:'2026-08-06T18:00:00Z',updatedAt:'2026-08-06T19:00:00Z'};
describe('community call state machine',()=>{
 it('loads a live call into muted preflight then goes live still muted',()=>{const loaded=communityCallReducer(initialCommunityCallState,{type:'LOADED',call});expect(loaded.phase).toBe('preflight');const connecting=communityCallReducer(loaded,{type:'CONNECTING'});const live=communityCallReducer(connecting,{type:'LIVE'});expect(live).toMatchObject({phase:'live',muted:true});});
 it('moves disconnected media to reconnecting and clears presence on summary',()=>{const active={...initialCommunityCallState,phase:'live' as const,call,participants:['p1']};expect(communityCallReducer(active,{type:'RECONNECTING'}).phase).toBe('reconnecting');expect(communityCallReducer(active,{type:'SUMMARY'})).toMatchObject({phase:'summary',participants:[],muted:true});});
 it('keeps connected media live when foreground state is synchronized',()=>{const active={...initialCommunityCallState,phase:'live' as const,call,muted:false,participants:['p1']};expect(communityCallReducer(active,{type:'SYNCED',call})).toMatchObject({phase:'live',muted:false,participants:['p1']});});
 it('clears media presence when a synchronized call has ended',()=>{const active={...initialCommunityCallState,phase:'reconnecting' as const,call,muted:false,participants:['p1'],activeSpeakers:['p1']};const ended={...call,status:'ended' as const,endedAt:'2026-08-06T19:30:00Z'};expect(communityCallReducer(active,{type:'SYNCED',call:ended})).toMatchObject({phase:'summary',muted:true,participants:[],activeSpeakers:[]});});
 it('removes a departed peer from both participant and speaker state',()=>{const active={...initialCommunityCallState,participants:['p1','p2'],activeSpeakers:['p1']};expect(communityCallReducer(active,{type:'PEER_LEFT',peerId:'p1'})).toMatchObject({participants:['p2'],activeSpeakers:[]});});
 it('keeps full, denied, unsupported and failed states distinct',()=>{for(const phase of ['full','denied','unsupported','failed'] as const)expect(communityCallReducer(initialCommunityCallState,{type:'ERROR',phase,message:phase}).phase).toBe(phase);});
});
