import { expect, it } from 'vitest';
import { refreshBlocked, registerReleaseDraftSaver, saveReleaseDrafts } from './releaseSafety';
it('blocks busy editors and propagates failed draft saves', async () => {
  const editor = document.createElement('div');
  editor.setAttribute('data-release-busy', 'true');
  document.body.append(editor);
  expect(refreshBlocked()).toBe(true);
  editor.remove();
  expect(refreshBlocked()).toBe(false);
  const unregister = registerReleaseDraftSaver(async () => { throw new Error('save failed'); });
  await expect(saveReleaseDrafts()).rejects.toThrow('save failed');
  unregister();
  await expect(saveReleaseDrafts()).resolves.toBeUndefined();
});
it('tracks form changes, edits during saves, and in-flight uploads', async () => {
  const { installReleaseSafety, releaseEditRevision } = await import('./releaseSafety');
  const originalFetch = window.fetch;
  const originalSend = XMLHttpRequest.prototype.send;
  let finish!: (response: Response) => void;
  window.fetch = () => new Promise(resolve => { finish = resolve; });
  installReleaseSafety();
  const input = document.createElement('input');
  document.body.append(input);
  const revision = releaseEditRevision();
  input.dispatchEvent(new Event('focusin', { bubbles: true }));
  input.value = 'draft';
  input.dispatchEvent(new Event('change', { bubbles: true }));
  expect(releaseEditRevision()).toBeGreaterThan(revision);
  expect(refreshBlocked()).toBe(true);
  input.value = '';
  input.dispatchEvent(new Event('input', { bubbles: true }));
  expect(refreshBlocked()).toBe(false);
  input.remove();
  expect(refreshBlocked()).toBe(false);
  const managed = document.createElement('textarea');
  managed.setAttribute('data-release-draft-managed', '');
  document.body.append(managed);
  managed.dispatchEvent(new Event('input', { bubbles: true }));
  expect(refreshBlocked()).toBe(false);
  const upload = window.fetch('/upload', { method: 'POST' });
  expect(refreshBlocked()).toBe(true);
  finish({ ok: true } as Response);
  await upload;
  expect(refreshBlocked()).toBe(false);
  managed.remove();
  window.fetch = originalFetch;
  XMLHttpRequest.prototype.send = originalSend;
});
