export enum ErrorCode {
  // Opportunities
  OPPORTUNITY_NOT_FOUND = "OPPORTUNITY_NOT_FOUND",
  OPPORTUNITY_VALIDATION_FAILED = "OPPORTUNITY_VALIDATION_FAILED",
  OPPORTUNITY_ALREADY_EXISTS = "OPPORTUNITY_ALREADY_EXISTS",
  OPPORTUNITY_EXPIRED = "OPPORTUNITY_EXPIRED",

  // Goals
  GOAL_NOT_FOUND = "GOAL_NOT_FOUND",
  GOAL_VALIDATION_FAILED = "GOAL_VALIDATION_FAILED",
  GOAL_ALREADY_EXISTS = "GOAL_ALREADY_EXISTS",

  // Profile
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_VALIDATION_FAILED = "PROFILE_VALIDATION_FAILED",

  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  // General
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",

  // AI
  AI_GENERATION_FAILED = "AI_GENERATION_FAILED",
  AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE",
  AI_RATE_LIMITED = "AI_RATE_LIMITED",
  AI_INVALID_RESPONSE = "AI_INVALID_RESPONSE",

  // Scraper
  SCRAPER_SOURCE_NOT_FOUND = "SCRAPER_SOURCE_NOT_FOUND",
  SCRAPER_JOB_FAILED = "SCRAPER_JOB_FAILED",
  SCRAPER_ALREADY_RUNNING = "SCRAPER_ALREADY_RUNNING",
  SCRAPER_INVALID_SOURCE = "SCRAPER_INVALID_SOURCE",

  // Payments / Billing
  PAYMENT_FAILED = "PAYMENT_FAILED",
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
  INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS",

  // Creator
  CREATOR_NOT_FOUND = "CREATOR_NOT_FOUND",
  CREATOR_ALREADY_VERIFIED = "CREATOR_ALREADY_VERIFIED",
  CREATOR_APPLICATION_REJECTED = "CREATOR_APPLICATION_REJECTED",
}
