import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { LogOut, Mic, MicOff, PhoneOff, RefreshCw, Volume2 } from 'lucide-react-native';
import { useTranslation } from 'react-i18next';
import { AnimatedPressable } from '../../ui/AnimatedPressable';
import { useTheme } from '../../context/ThemeContext';

export function VoiceCallRoom({ title, participants, speakers, muted, reconnecting, canEnd, onMute, onAudioRoute, onReconnect, onLeave, onEnd }: { title:string;participants:string[];speakers:string[];muted:boolean;reconnecting:boolean;canEnd:boolean;onMute:()=>void;onAudioRoute:()=>void;onReconnect:()=>void;onLeave:()=>void;onEnd:()=>void }) {
 const {t}=useTranslation('community'); const {colors}=useTheme();
 return <View testID="voice-call-room" style={styles.wrap}><Text style={[styles.title,{color:colors.foreground}]} numberOfLines={2}>{title}</Text><Text accessibilityLiveRegion="polite" style={[styles.status,{color:reconnecting?colors.warning:colors.success}]}>{reconnecting?t('calls.reconnecting'):t('calls.connected')}</Text><ScrollView contentContainerStyle={styles.people}>{participants.length?participants.map((id,index)=><View key={id} style={[styles.person,{borderColor:speakers.includes(id)?colors.accent:colors.border,backgroundColor:colors.card}]}><View style={[styles.avatar,{backgroundColor:`${colors.accent}18`}]}><Text style={{color:colors.accent,fontWeight:'800'}}>{index+1}</Text></View><Text style={[styles.personText,{color:colors.foreground}]} numberOfLines={1}>{t('calls.participant', {number:index+1})}</Text>{speakers.includes(id)&&<Text style={[styles.speaking,{color:colors.accent}]}>{t('calls.speaking')}</Text>}</View>):<Text style={[styles.empty,{color:colors.textSecondary}]}>{t('calls.waiting')}</Text>}</ScrollView><View style={styles.controls}><Control label={muted?t('calls.unmute'):t('calls.mute')} icon={muted?MicOff:Mic} onPress={onMute} color={muted?colors.error:colors.foreground} bg={colors.card}/><Control label={t('calls.audioRoute')} icon={Volume2} onPress={onAudioRoute} color={colors.foreground} bg={colors.card}/>{reconnecting&&<Control label={t('calls.reconnect')} icon={RefreshCw} onPress={onReconnect} color={colors.warning} bg={colors.card}/>}<Control label={t('calls.leave')} icon={LogOut} onPress={onLeave} color="#fff" bg={colors.error}/>{canEnd&&<Control label={t('calls.endEveryone')} icon={PhoneOff} onPress={onEnd} color={colors.error} bg={`${colors.error}16`}/>}</View></View>;
}
function Control({label,icon:Icon,onPress,color,bg}:{label:string;icon:React.ComponentType<{size:number;color:string}>;onPress:()=>void;color:string;bg:string}){return <View style={styles.controlWrap}><AnimatedPressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[styles.control,{backgroundColor:bg}]}><Icon size={21} color={color}/></AnimatedPressable><Text style={[styles.controlLabel,{color}]} numberOfLines={2}>{label}</Text></View>}
const styles=StyleSheet.create({wrap:{flex:1,padding:20},title:{fontSize:22,fontWeight:'800',textAlign:'center'},status:{fontSize:12,fontWeight:'700',textAlign:'center',marginTop:6},people:{paddingVertical:24,gap:8},person:{height:58,borderWidth:1,borderRadius:16,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:10},avatar:{width:36,height:36,borderRadius:12,alignItems:'center',justifyContent:'center'},personText:{flex:1,fontSize:14,fontWeight:'600'},speaking:{fontSize:11,fontWeight:'800'},empty:{fontSize:14,textAlign:'center',marginTop:40},controls:{flexDirection:'row',justifyContent:'center',alignItems:'flex-start',gap:12,flexWrap:'wrap',paddingBottom:16},controlWrap:{width:66,alignItems:'center'},control:{width:52,height:52,borderRadius:26,alignItems:'center',justifyContent:'center'},controlLabel:{fontSize:10,fontWeight:'700',textAlign:'center',marginTop:5}});
